server:
  port: 2002

spring:
  application:
    name: Goal
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    hikari:      schema: ${DB_SCHEMA}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true
    
    
